### ISSUE TITLE
Documentation a bit misleading...

### ISSUE THREAD

**Issue by jazzmind** [CakeDC/search#163]
The documentation suggests doing the following in the controller:
```
public $presetVars = [
        'query' => [
            'type' => 'query', 
            'method' => 'orConditions'
        ]
  ];
 $this->Paginator->settings['conditions'] = $this->Post->parseCriteria($this->Prg->parsedParams());
```
However, $this->Prg->parsedParams() returns null in this situation because when it gets initialised in Prg->presetForm() the code only handles "lookup", "checkbox" and "value" field types. The rest are skipped. 

```
$params = am($this->request->query, $this->Prg->parsedParams());
$this->Paginator->settings['conditions'] = $this->Post->parseCriteria($params);
```

The above code seems to work in a wider range of situations. I don't know if this is intended behavior, but if so perhaps the docs could be updated?

**Comment by antoniovassell** [comment]
I guess its about time to close this.

**Comment by omnuvito** [comment]
I think so too. Hi @jazzmind, I hope that @antoniovassell suggestion has helped you solve your doubt. If you need to clarify any other thing about this issue, We can open it again.
