### ISSUE TITLE
Hybrid Auth incompatibility

### ISSUE THREAD

**Issue by ecommy** [CakeDC/search#173]
I had both plugins installed and I got this error when trying to auth:
"Cannot access empty property"

so I ended adding inside PrgComponent just bellow init function
```
    public function init(Controller $controller) {		
```
this code:
```
    if($controller->request->params['controller'] == 'hybrid_auth') {
        return;
    }
```

**Comment by omnuvito** [comment]
Hi @ecommy, I hope you were able to solve the error, if not well, please let us know by sending the information that @antoniovassell asked you in the above comment and We can reopen the issue.
