### ISSUE TITLE
Integrate with TranslateBehavior

### ISSUE THREAD

**Issue by dungnguyen** [CakeDC/search#175]
Hi,

Thanks about a great plugin. But i have problem when want to using it with TranslateBehavior default of Cakephp.

When i using TranslateBehavior with field name. Everything ok. But when using filter with this field then i get error this field not exist. 

Any change can fix it ?

**Comment by stork** [comment]
```php
	public $filterArgs = array(
		'title' => array(
			'type' => 'query',
			'method' => 'searchTitleConditions',
		),
	);

	public function searchTitleConditions($data = array()) {
		if (empty($data['title'])) {
			return array();
		}

		return array('I18n__title.content LIKE' => '%' . $data['title'] . '%');
	}
```

**Comment by antoniovassell** [comment]
@dungnguyen I suppose @stork solved your issue. We'll close this.

**Comment by omnuvito** [comment]
Hi @dungnguyen, I hope you've been able to solve your issue. If not well, let us know and We can reopen the issue.
