### ISSUE TITLE
I have a problem when I use together plugin search and paginator 

### ISSUE THREAD

**Issue by vnt** [CakeDC/search#177]
Hi,

I have a problem when I use together plugin search and paginator (echo $this->Paginator->numbers, next and prev).
The url contains named parameter and query strings:
/admin/items/index/page:2?structure=&parent_id=27&lft=52&rght=147
Is there a way to have only query string?
Best regards,
D.

**Comment by deizel** [comment]
Sure, just load the core Paginator component like so:

````php
<?php
class AppController extends Controller {

    public $components = array(
        'Paginator' => array('paramType' => 'querystring'),
    );

}
````

See the book for other approaches: [Pagination with GET parameters](http://book.cakephp.org/2.0/en/core-libraries/components/pagination.html#pagination-with-get-parameters)

**Comment by dereuromark** [comment]
Or use Configure to do that :) See [here](https://github.com/dereuromark/cakephp-sandbox/blob/master/Config/configs.php#L120-L125)

**Comment by vnt** [comment]
I'm sorry,
I'have tried to insert  this:
<?php
class AppController extends Controller {
    public $components = array(
        'Paginator' => array('paramType' => 'querystring'),
    );
}
but my url is always this:
 /admin/items/index/page:2?structure=&parent_id=27&lft=52&rght=147

**Comment by dereuromark** [comment]
You didnt apply the above correctly.

**Comment by bhishmaRlx** [comment]
Thanks @deizel (y).
