### ISSUE TITLE
Multi word search

### ISSUE THREAD

**Issue by phpMagpie** [CakeDC/search#179]
Does the plugin have any options for splitting the query string into multiple words and searching that at least one occurrence of each word exists across all search fields?

**Comment by dereuromark** [comment]
That is a very specific use case. You might want to look into the hooks you can hook into.

**Comment by phpMagpie** [comment]
Hi @dereuromark thanks for the lightening fast response.  

Am I overthinking the problem then? WordPress comes as standard with search functionality which seems to do what I have requested.  You can see the search function in action here:
http://demo.opensourcecms.com/wordpress/?s=sample+example&submit=Search

The search query "sample example" matches "sample" in the title and "example" in the body.  

A query string of "sample 123123" returns no results, so it must be checking across multiple fields for at least one occurrence of each word.

Note: I reference WordPress's search as I'm replacing a WordPress site and need to match it's search functionality.

**Comment by dereuromark** [comment]
Did you try it? Or did you look at the source code?
The basic behavior of what you describe is already implemented it seems:
https://github.com/CakeDC/search/blob/master/Model/Behavior/SearchableBehavior.php#L358

**Comment by phpMagpie** [comment]
Mark, thanks for bringing my attention to that function.  I had not tried the 'connectorOr' setting as I could find no mention of it in the documentation.

Took me some time to figure out how to properly apply this setting and it didn't quite seem to do what I wanted, but it was close.  I settled with creating a custom function to generate my conditions.

Thanks for your time!
