### ISSUE TITLE
Error in composer.json and plugin not up to date with recent core changes.

### ISSUE THREAD

**Issue by burzum** [CakeDC/search#182]
There are at least two issues:

* Line 29 in composer.json (`"cakephp/app": "dev-master",`) causes an error for composer when trying to run composer install, remove that line
* After fixing that locally and being able to run unit tests I've got this: Fatal error: Class 'Cake\Utility\Folder' not found in vendor\cakedc\search\tests\bootstrap.php on line 51

The second one means the plugin does not reflect the most recent changes in the core.

Travis fails because of that and I could not run tests locally either. See the failed travis build here, same issue as local. https://github.com/CakeDC/search/pull/181

Also, how do I need to set the plugin up to be able to run unit tests? I've seen that other plugins including my own can run the tests without any special set up. Just do a composer install from inside the cloned plugins folder and run phpunit.

**Comment by deizel** [comment]
Sorry @burzum, this should be resolved now that #176 has been merged.

**Comment by burzum** [comment]
Yes, thanks.
