### ISSUE TITLE
Flexible value for defaultValue and population into form field

### ISSUE THREAD

**Issue by Lou2401** [CakeDC/search#183]
Hi,

I am looking for a possibility to have a value which is filled into the defaultValue option filled in also into the search form field. Further I like to know what's the best way to use a calculated value to set the defaultValue option. 

A use case would be that a default search runs which uses the current date for a date field search. My search form is on the same page as the search result. The search form should then show on first visit the date on today with the results of date = today.

Thanks for any help on this issue.
Kind regards
Marco

**Comment by pmoraes** [comment]
Hello @Lou2401,

I cannot understand your real suggestion, are you suggesting in we have a default value to search always?

in your example, are you  talking about to have a default filter?

if we don't have any filter, will we use the default value? in your example is the date, right?

**Comment by Lou2401** [comment]
Hi @pmoraes,

yes that's right.

**Comment by pmoraes** [comment]
Hello @Lou2401,

I'm working in this issue, today we have the defaultValue settings working fine. You want just to put a filter with date? is that your problem?

if yes, you can to do a custom query to do that.

By any doubt, let me know.

Thanks.

**Comment by Lou2401** [comment]
Hi @pmoraes,

Yes, I use the plugin for CakePHP 2.x.

I am aware about the custom query functionality and also make already use of it. But if I am not wrong then the custom query function is only called if a search request is sent via form request to the plugin already.

Now I ask for a possibility to configure a field with a default value, not only a fixed value, but also a "calculated" value. Example would be to call a function to get back the current date.

If the search form fields are then build for the view then the field value of the search form shall also show this defaulted (calculated) value already.

So it is basically about calling a kind of a custom query function in order to determine a default value. Today we have the default value option available but as far as I see no chance to set this default value in a flexible way.

Regards
Marco

**Comment by antoniovassell** [comment]
Hey @pmoraes @Lou2401 Is this issue resolved for you or do we need to attack it some more?

**Comment by Megslalk** [comment]
Hi! closing this issue, please reopen if still needed.
