### ISSUE TITLE
3.0: Does not reset page

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/search#186]
In 3.x version the plugin does not reset page on filtering as it did before.
The result is a NotFoundException when you are on page 3 for example and you search for a term that would result in less pages. Manually removing the "page=3" part from the URL makes it work again.

But the component should reset this automatically.

**Comment by dereuromark** [comment]
A fix would be: https://github.com/CakeDC/search/compare/3.0...dereuromark:3.0
But I think the param joggling should be cleaned up in general...

**Comment by deizel** [comment]
Closing since #118 has been merged.
