### ISSUE TITLE
Use 'search_with_connectors' in $filterArgs

### ISSUE THREAD

**Issue by kostalihas** [CakeDC/search#199]
i dont know where I am wrong ;iwant search for exemple php+sql+java,html5 the connector must do
Competence.competence=php and Competence.competence=sql and Competence.competence=java or Competence.competence=html5

this is my model User.php

public $hasAndBelongsToMany = array(
		'Competence' => array(
			'with' => 'CompetencesUser',
			'className' => 'Competence',
			'joinTable' => 'competences_users',
			'foreignKey' => 'user_id',
			'associationForeignKey' => 'competence_id',
			'unique' => 'keepExisting',
		)
	);

public $filterArgs = array(
        'username' => array(
            'type' => 'value'
        ),
        'nom' => array(
            'type' => 'like'
        ),
        'prenom' => array(
            'type' => 'like'
        ),
        'email' => array(
            'type' => 'value'
        ),
        'competences' => array(
            'type' => 'subquery',
            'method' => 'findByCompetences',
            'field' => 'User.id',
            'before' => true
        ),
            
            'search_with_connectors' => array(
        'type' => 'like',
        'field' => 'Competence.competence',
        'connectorAnd' => '+', 'connectorOr' => ','
    )
        );

 public function findByCompetences($data = array()) {

        $this->CompetencesUser->Behaviors->attach('Containable', array(
                'autoFields' => false
            )
        );

        $this->CompetencesUser->Behaviors->attach('Search.Searchable');
       
        $query = $this->CompetencesUser->getQuery('all', array(
            'conditions' =>
        array(
       
        'Competence.competence' => $data['competences'],

        ),
        'fields' => array(
                'user_id'
            ),
            'contain' => array(
                'Competence'
            )

        ));
         return $query;
    }

**Comment by kostalihas** [comment]
this is the request result of my search

SELECT `User`.`id`, `User`.`username`, `User`.`nom`, `User`.`prenom`, `User`.`email`, `User`.`password`, `User`.`created`, `User`.`modified` FROM `dcsearch`.`users` AS `User` WHERE User.id in (SELECT `CompetencesUser`.`user_id` FROM `dcsearch`.`competences_users` AS `CompetencesUser` LEFT JOIN `dcsearch`.`competences` AS `Competence` ON (`CompetencesUser`.`competence_id` = `Competence`.`id`) WHERE `Competence`.`competence` = 'php+sql+java,html') LIMIT 20

**Comment by pmoraes** [comment]
Hi @kostalihas, could you see my comment in this link? 
https://github.com/CakeDC/search/issues/201#issuecomment-148780243

By any doubt, please let me know.

Thanks,

Peter Moraes.

**Comment by Megslalk** [comment]
Hi, Closing this issue, please reopen if still unresolved.
