### ISSUE TITLE
i want use search with and/or connectors 

### ISSUE THREAD

**Issue by kostalihas** [CakeDC/search#201]
I want search by competence forexample $data['competences'] =java+oracle,sql then the method of the request competence must know java is first oracle is second and sql is third.

i have this Error Invalid argument supplied for foreach()
i guess the prb is in $data = array('competences' =>'First%+Second%, Third%');
or at $result = $this->CompetencesUser->parseCriteria($data);

in my query request i have this surprise:

SELECT User.id, User.username, User.nom, User.prenom, User.email, User.password, User.created, User.modified FROM dcsearch.users AS User WHERE User.id in (SELECT CompetencesUser.user_id FROM dcsearch.competences_users AS CompetencesUser LEFT JOIN dcsearch.competences AS Competence ON (CompetencesUser.competence_id = Competence.id) WHERE ((((Competence.competence LIKE '%First\%%') AND (Competence.competence LIKE '%Second\%%'))) OR (Competence.competence LIKE '%Third\%%'))) LIMIT 20

this is my model user.php

im my $filterArgs
'competences' => array(
            'type' => 'subquery',
            'method' => 'findByCompetences',
            'field' => 'User.id',       
         'connectorsAnd' => '+', 
         'connectorOr' => ',',
          'before' => true,
           'after' => true           
);
in my method findByCompetences

 public function findByCompetences($data = array()) {

        $this->CompetencesUser->Behaviors->attach('Containable', array(
                'autoFields' => false
            )
        );
        $this->CompetencesUser->Behaviors->attach('Search.Searchable');
        $data = array('competences' => 'First%+Second%, Third%');

        $result = $this->CompetencesUser->parseCriteria($data);
        
        $expected = array(0 => array('OR' => array(
			array('AND' => array(
				array('Competence.competence LIKE' => '%First\%%'),
				array('Competence.competence LIKE' => '%Second\%%'),
			)),
			array('AND' => array(
				array('Competence.competence LIKE' => '%Third\%%')
			)),
		)));
		
    
        $query = $this->CompetencesUser->getQuery('all', array(
        	
           'conditions' =>array(
           	$expected,
           	$result), 
            'fields' => array(
              'user_id'
           ),
            'contain' => array(
               'Competence'
 )));
           return $query;
    }

**Comment by pmoraes** [comment]
Hi @kostalihas,

I was analysing your problem, and I saw that you are wanting to use connectorAnd and connectorOr together with subquery right?

The plugin has a method called "condLike", could you see it here https://github.com/CakeDC/search/blob/master/Model/Behavior/SearchableBehavior.php#L210-L230

There you can see the way how to you will use to do your conditions. 

and I think that you have the same problem in this issue: https://github.com/CakeDC/search/issues/199

if it solve your problem, please let me know to close these issues.

Thanks,

Peter Moraes.

**Comment by antoniovassell** [comment]
Hey @kostalihas did @pmoraes suggestion helped?

**Comment by Megslalk** [comment]
Hi, closing this issue, please reopen if still needed.
