### ISSUE TITLE
Trying to search on multiple fields

### ISSUE THREAD

**Issue by BrandTurner** [CakeDC/search#208]
I'm trying to run a search with an OR condition that looks at multiple fields to find a match. Take these tuples as an example
```
   name        short_naame        id
1. John        foo                bar 
2. Baz         John               Hello
3. Dave        Mike               John
```

If I search for John, I want to return all 3 rows. I read through the documenation, but cannot get it working. In my model, I have:
```php
public $filterArgs = array(
		'name' => array(
			'type' 	=> 'like'
		),
		'filter' => array(
			'type' => 'query',
			'method' => 'orConditions'
		),
	);
...
public function orConditions($data = array()) {
		$filter = $data['filter'];
		$condition = array(
			'OR' => array(
				$this->alias . '.name LIKE' 		=> '%' . $filter . '%',
				$this->alias . '.id LIKE' 			=> '%' . $filter . '%',
				$this->alias . '.short_name LIKE' 	=> '%' . $filter . '%',
			)
		);
		return $condition;
	}
```
However, with the sample data above, if I search for 'John', it will only return row one instead of all 3 rows. My problem is that I am unsure about the part of the documentation that states this:

"In this example the search by OR condition is shown. For this purpose we defined the method orConditions() and added the filter method."

```php
array(
    'name' => 'filter',
    'type' => 'query',
    'method' => 'orConditions'
)
```

Where does the above snippet of code below and how would I return all 3 rows?

**Comment by dereuromark** [comment]
Why are you not just using

    'type' => 'like',
    'field' => [field1, field2, field3]

?

**Comment by BrandTurner** [comment]
Thanks! It worked like a charm.
