### ISSUE TITLE
SearchableBehavior has no support for 'checkbox' type

### ISSUE THREAD

**Issue by nemmons** [CakeDC/search#211]
As far as I can tell, the 'checkbox' filterArg type is completely unhandled in the [parseCriteria()](https://github.com/CakeDC/search/blob/master/Model/Behavior/SearchableBehavior.php#L89) method of SearchableBehavior.

I was not able to get my checkbox-based filters to work locally until I added 'checkbox' to the list of acceptable types ([line 103](https://github.com/CakeDC/search/blob/master/Model/Behavior/SearchableBehavior.php#L103)).

If someone can confirm that I'm not missing something I'm happy to create a pull request to update this.

**Comment by dereuromark** [comment]
A checkbox is just a boolean toggle with type value. You should set the default value to 0 here then.

**Comment by nemmons** [comment]
I'm sorry, I think I perhaps did not explain very well what my problem was. In the parseCriteria() method i referred to, there's an if-elseif-...-elseif block that adds different searchconditions depending on the type of the filterArg as defined in the model. If you define a filterArg of type 'checkbox', this if-elseif block does not add any conditions and so does not filter anything

**Comment by dereuromark** [comment]
OK, but the fieldset form type (controller => view) does not have to map to the model layer form type.
In your case you would have to overwrite the model type "value" with "checkbox" in your controller for the presentation afaik.
I could be wrong, but I remember something like that from back in the days.

**Comment by nemmons** [comment]
Oh. wow, I see now. I'm sorry, I was very horribly misreading the documentation. Thank you for your help and pointing me in the right direction.
