### ISSUE TITLE
Search on translate fields

### ISSUE THREAD

**Issue by djonatanb** [CakeDC/search#226]
I'm trying to find out if the plugin can search inside translated fields, in my case I have titles saved in two languages that I set up using the Translat Behavior and all the instructions found here http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations

**Comment by andtxr** [comment]
I will take a look.

**Comment by andtxr** [comment]
After a little bit of research, here we go:

1 - Create a new finder method in your table class. Let`s take in consideration an **ArticlesTable** that we would like to search for it **title**:

```php
    public function findWithTranslated(Query $query, array $options) {
        $field = $options['field']['name'];
        $filter = $options[$field];
        $query->where([
            "Articles.{$field} LIKE" => '%' . $filter . '%'
        ]);
        return $query->orWhere([
            "Articles_{$field}_translation.content LIKE" => '%' . $filter . '%'
        ]);
    }
```
2 - Then we relate it to an field:

```php
    public $filterArgs = array(
        'title' => array(
            'type' => 'finder',
            'finder' => 'WithTranslated'
        )
    );
```

We are done!

**Comment by Megslalk** [comment]
Closing issue - please reopen if further assistance is required!
